baseURL = "http://precisionwrapandtint.com/"
languageCode = "en-us"
theme = "navigator-hugo"
title = "Precision Wrap and Tint"
[Languages.en]
dateFormat = "January 2, 2006"
footerAboutTitle = "About"
footerDescription = "Providing quality wraps and tints to the LA area."
footerQuicklinkTitle = "Quicklinks"
footerServiceTitle = "Service"
SubscribeTitle = "Subscribe"
languageCode = "en-us"
logo = "images/logo.png"
menufixed = false
title = "Precision Wrap and Tint"
weight = 2
[Languages.en.params.aboutSm]
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"
enable = true
title = "We have explored the digital landscape with passion for a long time"
[Languages.en.params.blog]
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
title = "Blog."
topTitle = "OUR UNTOLD STORY"
[Languages.en.params.contact]
address = "1724 Border Avenue <br> Torrance, CA 90501"
dribbble = "https://dribbble.com/"
enable = true
facebook = "https://www.facebook.com/"
fax = "+61 3827 3590"
instagram = "https://www.instagram.com/"
linkedin = "https://www.linkedin.com/"
mapLatitude = "51.507351"
mapLongitude = "-0.127758"
mapMarker = "images/marker.png"
phone = "(03) 9283 2617"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
title = "Contact Us."
topTitle = "DROP US A NOTE"
twitter = "https://twitter.com/"
[Languages.en.params.cta]
bg = "images/call-to-action/call-to-action-bg-2.jpg"
btnText = "Contact Us"
enable = true
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
title = "Let's Create Something Together"
[Languages.en.params.hero]
btnText = "Know More"
btnURL = "https://themefisher.com/"
button = true
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
enable = true
heading = "Precision Wrap and Tint"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL = "https://www.youtube.com/embed/g3-VxLQO7do"
